version: "3"

services:
  backend:
    environment:
      DJANGO_ENV: production
      SECRET_KEY: "${SECRET_KEY}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    expose:
      - "8001"
    volumes:
      - ./nginx/www/app/static:/var/www/app/static
      - ./nginx/www/app/media:/var/www/app/media
    command: uwsgi --socket :8001 --module config.wsgi --env DJANGO_SETTINGS_MODULE=config.settings.production

  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: management
      MYSQL_USER: django
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
    networks:
      - service-net

  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/www/app/static:/var/www/app/static
      - ./nginx/www/app/media:/var/www/app/media
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
    depends_on:
      - backend
      - db
    networks:
      - service-net
    command: nginx -g 'daemon off;'

  elasticsearch:
    container_name: elastic1
    build:
      context: elk/elasticsearch
    hostname: doc-elastic101
    ports:
      - "9200:9200"
      - "9300:9300"
#    deploy:
#      resources:
#        limits:
#          memory: 2G
    networks:
      service-net:
        ipv4_address: 172.60.0.2
    volumes:
#      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch-data:/usr/share/elasticsearch/data
    extra_hosts:
      - "doc-kibana101:172.60.0.4"
      - "doc-logstash101:172.60.0.3"

  logstash:
    build:
      context: elk/logstash/
    container_name: logstash1
    hostname: doc-logstash101
    ports:
      #      - "5043-5100:5043-5100/tcp"
      - "5043:5043/tcp"
    #    deploy:
    #      resources:
    #        limits:
    #          memory: 1G
    networks:
      service-net:
        ipv4_address: 172.60.0.3
    extra_hosts:
      - "doc-elastic101:172.60.0.2"
      - "doc-kibana101:172.60.0.4"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #    depends_on:
  #      - elasticsearch

  kibana:
    build:
      context: elk/kibana/
    hostname: doc-kibana101
    container_name: kibana1
    ports:
      - "5601:5601"
    #    deploy:
    #      resources:
    #        limits:
    #          memory: 512M
    networks:
      service-net:
        ipv4_address: 172.60.0.4
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    extra_hosts:
      - "doc-elastic101:172.60.0.2"
      - "doc-logstash101:172.60.0.3"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
