version: "3.2"

services:
  backend:
    container_name: backend
    build:
      context: ./django
    environment:
      DJANGO_ENV: develop
    volumes:
      - './django/app:/opt/app'
    networks:
      - service-net
    command:
      bash -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: frontend
    build:
      context: ./nextjs
    networks:
      - service-net
    restart: always
    command: pm2-runtime start npm -- start

networks:
  service-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.60.0.0/16