version: "3"

services:
  app:
    container_name: app
    build:
      context: ./django
    environment:
      DJANGO_ENV: develop
    volumes:
      - './django/app:/opt/app'
    networks:
      - service-net
    command:
      bash -c "python manage.py runserver 0.0.0.0:8000"

networks:
  service-net:
    driver: bridge